// MCP server (stdio or HTTP) for Claude Desktop / Claude Code integration.
#![allow(dead_code)] // helpers are invoked through spawn_blocking/macro-generated code
// docs: https://docs.rs/rmcp/latest/rmcp/
// MCP spec: https://modelcontextprotocol.io/

use rmcp::{
    ServerHandler, ServiceExt,
    handler::server::{
        router::tool::ToolRouter,
        wrapper::Parameters,
    },
    model::*,
    tool, tool_handler, tool_router,
    transport::stdio,
};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use crate::{
    config::{Config, collection_db_path},
    db,
    index,
};

// ^ don't import crate::error::Result here — macro-generated code uses
//   std::result::Result<T,E> (2 params) and the name must not be shadowed.
type IrResult<T> = std::result::Result<T, crate::error::Error>;

// ── tool input types ──────────────────────────────────────────────────────────

#[derive(Debug, Deserialize, JsonSchema)]
struct SearchInput {
    /// Search query text
    query: String,
    /// Search mode: bm25, vector, or hybrid (default: hybrid)
    mode: Option<String>,
    /// Maximum number of results to return (default: 10)
    limit: Option<usize>,
    /// Minimum relevance score 0.0–1.0 (default: none)
    min_score: Option<f64>,
    /// Restrict search to these collection names (default: all)
    collections: Option<Vec<String>>,
}

#[derive(Debug, Deserialize, JsonSchema)]
struct UpdateInput {
    /// Only update this collection name (default: all collections)
    collection: Option<String>,
    /// Force full re-index from scratch (default: false)
    force: Option<bool>,
}

// ── status / update output types ──────────────────────────────────────────────

#[derive(Serialize)]
struct CollectionStatus {
    name: String,
    path: String,
    indexed: bool,
    size_mb: f64,
    doc_count: Option<usize>,
}

#[derive(Serialize)]
struct StatusOutput {
    collections: Vec<CollectionStatus>,
    daemon_running: bool,
}

#[derive(Serialize)]
struct UpdateResult {
    collection: String,
    added: usize,
    updated: usize,
    deactivated: usize,
}

// ── server ────────────────────────────────────────────────────────────────────

#[derive(Clone)]
struct IrMcpServer {
    // ^ tool_router field is injected by #[tool_router] at compile time
    tool_router: ToolRouter<Self>,
}

impl IrMcpServer {
    fn new() -> Self {
        // ^ Self::tool_router() is generated by #[tool_router] — pre-wired with all tools
        Self { tool_router: Self::tool_router() }
    }
}

#[tool_router]
impl IrMcpServer {
    #[tool(description = "Hybrid BM25+vector search over indexed document collections. \
        Returns ranked results with file path, title, relevance score, and a text snippet. \
        Use the file path with a file-read tool to retrieve full document content.")]
    async fn search(&self, params: Parameters<SearchInput>) -> String {
        let input = params.0;
        let query = input.query.clone();
        let mode = input.mode.clone().unwrap_or_else(|| "hybrid".to_string());
        let limit = input.limit.unwrap_or(10);
        let min_score = input.min_score;
        let collections = input.collections.clone().unwrap_or_default();

        match tokio::task::spawn_blocking(move || {
            crate::search_core(&query, &mode, limit, min_score, &collections, false)
        })
        .await
        {
            Ok(Ok(results)) => tool_ok_json(&results),
            Ok(Err(e)) => tool_err(e.to_string()),
            Err(e) => tool_err(format!("internal: {e}")),
        }
    }

    #[tool(description = "Show index health: collection names, paths, document counts, \
        DB sizes, and whether the search daemon is running.")]
    async fn status(&self) -> String {
        match tokio::task::spawn_blocking(build_status).await {
            Ok(Ok(out)) => tool_ok_json(&out),
            Ok(Err(e)) => tool_err(e.to_string()),
            Err(e) => tool_err(format!("internal: {e}")),
        }
    }

    #[tool(description = "Re-index document collections so newly added or changed files \
        become searchable. Runs synchronously — may take seconds to minutes for large collections.")]
    async fn update(&self, params: Parameters<UpdateInput>) -> String {
        let input = params.0;
        let collection = input.collection.clone();
        let force = input.force.unwrap_or(false);

        match tokio::task::spawn_blocking(move || run_update(collection.as_deref(), force)).await {
            Ok(Ok(results)) => tool_ok_json(&results),
            Ok(Err(e)) => tool_err(e.to_string()),
            Err(e) => tool_err(format!("internal: {e}")),
        }
    }
}

#[tool_handler]
impl ServerHandler for IrMcpServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(
            ServerCapabilities::builder().enable_tools().build(),
        )
        .with_server_info(Implementation::new("ir", env!("CARGO_PKG_VERSION")))
        .with_instructions(build_instructions())
    }
}

// ── tool response helpers ─────────────────────────────────────────────────────

/// Serialize a value to pretty JSON; propagate serialization failures as errors.
fn tool_ok_json(v: &impl Serialize) -> String {
    match serde_json::to_string_pretty(v) {
        Ok(s) => s,
        Err(e) => tool_err(format!("serialization failed: {e}")),
    }
}

/// Produce a safe JSON error object (escapes all user-controlled content).
fn tool_err(msg: String) -> String {
    // ^ use serde_json to avoid JSON injection from error messages containing quotes
    serde_json::json!({"error": msg}).to_string()
}

// ── server instructions ───────────────────────────────────────────────────────

fn build_instructions() -> String {
    let Ok(config) = Config::load() else {
        return "ir local search engine. No collections configured. \
                Run `ir collection add <name> <path>` to add one."
            .to_string();
    };
    if config.collections.is_empty() {
        return "ir local search engine. No collections configured. \
                Run `ir collection add <name> <path>` to add one."
            .to_string();
    }

    let cols: Vec<String> = config
        .collections
        .iter()
        .map(|c| {
            let db_path = collection_db_path(&c.name);
            let suffix = if db_path.exists() {
                count_docs(&db_path)
                    .map(|n| format!(", {n} docs"))
                    .unwrap_or_default()
            } else {
                " (not indexed)".to_string()
            };
            format!("{} ({}{})", c.name, c.path, suffix)
        })
        .collect();

    format!(
        "ir local search engine. Collections: {}. \
        Use `search` for hybrid BM25+vector retrieval, `status` for index health, \
        `update` to re-index after file changes. \
        Results include file paths — use a file-read tool to fetch full document content.",
        cols.join("; ")
    )
}

// ── helpers ───────────────────────────────────────────────────────────────────

fn count_docs(db_path: &std::path::Path) -> Option<usize> {
    db::ensure_sqlite_vec();
    let conn = rusqlite::Connection::open_with_flags(
        db_path,
        rusqlite::OpenFlags::SQLITE_OPEN_READ_ONLY,
    )
    .ok()?;
    conn.query_row(
        "SELECT COUNT(*) FROM documents WHERE active = 1",
        [],
        |row| row.get::<_, usize>(0),
    )
    .ok()
}

fn build_status() -> IrResult<StatusOutput> {
    let config = Config::load()?;
    let mut collections = Vec::new();
    for col in &config.collections {
        let db_path = collection_db_path(&col.name);
        let indexed = db_path.exists();
        let size_mb = if indexed {
            std::fs::metadata(&db_path).map(|m| m.len()).unwrap_or(0) as f64 / 1_048_576.0
        } else {
            0.0
        };
        let doc_count = if indexed { count_docs(&db_path) } else { None };
        collections.push(CollectionStatus {
            name: col.name.clone(),
            path: col.path.clone(),
            indexed,
            size_mb,
            doc_count,
        });
    }
    Ok(StatusOutput {
        collections,
        daemon_running: crate::daemon::is_running(),
    })
}

fn run_update(collection: Option<&str>, force: bool) -> IrResult<Vec<UpdateResult>> {
    let config = Config::load()?;
    let cols: Vec<_> = match collection {
        Some(name) => {
            let c = config
                .get_collection(name)
                .ok_or_else(|| crate::error::Error::CollectionNotFound(name.to_string()))?;
            vec![c]
        }
        None => config.collections.iter().collect(),
    };

    let mut results = Vec::new();
    for col in cols {
        let db_path = collection_db_path(&col.name);
        let pp_aliases = col.preprocessor.as_deref().unwrap_or(&[]);
        let has_preprocessor = !config.resolve_preprocessor_commands(pp_aliases).is_empty();
        let db_conn = db::CollectionDb::open(&col.name, &db_path, has_preprocessor)?;
        let opts = index::UpdateOptions { force };
        let (added, updated, deactivated) = index::update(&db_conn, col, &opts, &config)?;
        results.push(UpdateResult {
            collection: col.name.clone(),
            added,
            updated,
            deactivated,
        });
    }
    Ok(results)
}

// ── entry point ───────────────────────────────────────────────────────────────

pub async fn run(http: Option<u16>) -> IrResult<()> {
    match http {
        None => run_stdio().await,
        Some(port) => run_http(port).await,
    }
}

async fn run_stdio() -> IrResult<()> {
    let service = IrMcpServer::new()
        .serve(stdio())
        .await
        .map_err(|e| crate::error::Error::Other(e.to_string()))?;
    service
        .waiting()
        .await
        .map_err(|e| crate::error::Error::Other(e.to_string()))?;
    Ok(())
}

async fn run_http(port: u16) -> IrResult<()> {
    use rmcp::transport::streamable_http_server::{
        StreamableHttpServerConfig, StreamableHttpService,
        session::local::LocalSessionManager,
    };

    let service = StreamableHttpService::new(
        || Ok(IrMcpServer::new()),
        LocalSessionManager::default().into(),
        StreamableHttpServerConfig::default(),
    );

    let addr = format!("0.0.0.0:{port}");
    let listener = tokio::net::TcpListener::bind(&addr)
        .await
        .map_err(|e| crate::error::Error::Other(format!("bind {addr}: {e}")))?;
    eprintln!("ir MCP server listening on http://{addr}/mcp");

    let router = axum::Router::new().nest_service("/mcp", service);
    axum::serve(listener, router)
        .with_graceful_shutdown(async {
            tokio::signal::ctrl_c().await.ok();
        })
        .await
        .map_err(|e| crate::error::Error::Other(e.to_string()))
}
