// MCP server (stdio or HTTP) for Claude Desktop / Claude Code integration.
#![allow(dead_code)] // helpers are invoked through spawn_blocking/macro-generated code
// docs: https://docs.rs/rmcp/latest/rmcp/
// MCP spec: https://modelcontextprotocol.io/

use rmcp::{
    ServerHandler, ServiceExt,
    handler::server::{
        router::tool::ToolRouter,
        wrapper::Parameters,
    },
    model::*,
    tool, tool_handler, tool_router,
    transport::stdio,
};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use rusqlite::{Connection, OpenFlags};

use crate::{
    config::{Config, collection_db_path},
    db,
    index,
};

// ^ don't import crate::error::Result here — macro-generated code uses
//   std::result::Result<T,E> (2 params) and the name must not be shadowed.
type IrResult<T> = std::result::Result<T, crate::error::Error>;

// ── tool input types ──────────────────────────────────────────────────────────

#[derive(Debug, Deserialize, JsonSchema)]
struct SearchInput {
    /// Search query text
    query: String,
    /// Search mode: bm25, vector, or hybrid (default: hybrid)
    mode: Option<String>,
    /// Maximum number of results to return (default: 10)
    limit: Option<usize>,
    /// Minimum relevance score 0.0–1.0 (default: none)
    min_score: Option<f64>,
    /// Restrict search to these collection names (default: all)
    collections: Option<Vec<String>>,
}

#[derive(Debug, Deserialize, JsonSchema)]
struct UpdateInput {
    /// Only update this collection name (default: all collections)
    collection: Option<String>,
    /// Force full re-index from scratch (default: false)
    force: Option<bool>,
}

#[derive(Debug, Deserialize, JsonSchema)]
struct GetInput {
    /// File path to retrieve. Exact match first, then suffix match, then substring.
    path: String,
    /// Restrict lookup to these collection names (default: all)
    collections: Option<Vec<String>>,
}

#[derive(Debug, Deserialize, JsonSchema)]
struct MultiGetInput {
    /// List of file paths to retrieve.
    paths: Vec<String>,
    /// Restrict lookup to these collection names (default: all)
    collections: Option<Vec<String>>,
}

// ── get / multi_get output types ─────────────────────────────────────────────

#[derive(Serialize)]
struct DocContent {
    collection: String,
    path: String,
    title: String,
    content: String,
}

#[derive(Serialize)]
struct MultiGetResult {
    found: Vec<DocContent>,
    /// Paths that had no match in any collection
    not_found: Vec<String>,
}

// ── status / update output types ──────────────────────────────────────────────

#[derive(Serialize)]
struct CollectionStatus {
    name: String,
    path: String,
    indexed: bool,
    size_mb: f64,
    doc_count: Option<usize>,
}

#[derive(Serialize)]
struct StatusOutput {
    collections: Vec<CollectionStatus>,
    daemon_running: bool,
}

#[derive(Serialize)]
struct UpdateResult {
    collection: String,
    added: usize,
    updated: usize,
    deactivated: usize,
}

// ── server ────────────────────────────────────────────────────────────────────

#[derive(Clone)]
struct IrMcpServer {
    // ^ tool_router field is injected by #[tool_router] at compile time
    tool_router: ToolRouter<Self>,
}

impl IrMcpServer {
    fn new() -> Self {
        // ^ Self::tool_router() is generated by #[tool_router] — pre-wired with all tools
        Self { tool_router: Self::tool_router() }
    }
}

#[tool_router]
impl IrMcpServer {
    #[tool(description = "Hybrid BM25+vector search over indexed document collections. \
        Returns ranked results with file path, title, relevance score, and a text snippet. \
        Use the file path with a file-read tool to retrieve full document content.")]
    async fn search(&self, params: Parameters<SearchInput>) -> Result<String, String> {
        let SearchInput { query, mode, limit, min_score, collections } = params.0;
        let mode = mode.unwrap_or_else(|| "hybrid".to_string());
        let limit = limit.unwrap_or(10);
        let collections = collections.unwrap_or_default();
        spawn_tool(move || {
            crate::search_core(&query, &mode, limit, min_score, &collections, crate::types::Verbosity::Quiet)
        }).await
    }

    #[tool(description = "Show index health: collection names, paths, document counts, \
        DB sizes, and whether the search daemon is running.")]
    async fn status(&self) -> Result<String, String> {
        spawn_tool(build_status).await
    }

    #[tool(description = "Re-index document collections so newly added or changed files \
        become searchable. Runs synchronously — may take seconds to minutes for large collections.")]
    async fn update(&self, params: Parameters<UpdateInput>) -> Result<String, String> {
        let UpdateInput { collection, force } = params.0;
        let force = force.unwrap_or(false);
        spawn_tool(move || run_update(collection.as_deref(), force)).await
    }

    #[tool(description = "Retrieve the full text of a single document by file path. \
        Tries exact match first, then suffix match, then substring match across all collections. \
        Use this when search returns a path you want to read in full.")]
    async fn get(&self, params: Parameters<GetInput>) -> Result<String, String> {
        let GetInput { path, collections } = params.0;
        let collections = collections.unwrap_or_default();
        spawn_tool(move || {
            fetch_document(&path, &collections)?
                .ok_or_else(|| crate::error::Error::Other(format!("not found: {path}")))
        }).await
    }

    #[tool(description = "Retrieve the full text of multiple documents by file path in one call. \
        Each path is resolved independently (exact → suffix → substring match). \
        Returns found documents and a list of unmatched paths.")]
    async fn multi_get(&self, params: Parameters<MultiGetInput>) -> Result<String, String> {
        let MultiGetInput { paths, collections } = params.0;
        let collections = collections.unwrap_or_default();
        spawn_tool(move || {
            let config = Config::load()?;
            let mut found = Vec::new();
            let mut not_found = Vec::new();
            for path in &paths {
                match fetch_document_with_config(path, &collections, &config)? {
                    Some(doc) => found.push(doc),
                    None => not_found.push(path.clone()),
                }
            }
            Ok(MultiGetResult { found, not_found })
        }).await
    }
}

#[tool_handler]
impl ServerHandler for IrMcpServer {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(
            ServerCapabilities::builder().enable_tools().build(),
        )
        .with_server_info(Implementation::new("ir", env!("CARGO_PKG_VERSION")))
        .with_instructions(build_instructions())
    }
}

// ── tool response helpers ─────────────────────────────────────────────────────

/// Run a blocking function on a thread pool and return its result as JSON.
async fn spawn_tool<F, T>(f: F) -> Result<String, String>
where
    F: FnOnce() -> IrResult<T> + Send + 'static,
    T: Serialize + Send + 'static,
{
    match tokio::task::spawn_blocking(f).await {
        Ok(Ok(v)) => ok_json(&v),
        Ok(Err(e)) => Err(e.to_string()),
        Err(e) => Err(format!("internal: {e}")),
    }
}

fn ok_json(v: &impl Serialize) -> Result<String, String> {
    serde_json::to_string_pretty(v).map_err(|e| format!("serialization failed: {e}"))
}

// ── server instructions ───────────────────────────────────────────────────────

fn build_instructions() -> String {
    let config = Config::load().ok().filter(|c| !c.collections.is_empty());
    let Some(config) = config else {
        return "ir local search engine. No collections configured. \
                Run `ir collection add <name> <path>` to add one."
            .to_string();
    };

    let cols: Vec<String> = config
        .collections
        .iter()
        .map(|c| {
            let db_path = collection_db_path(&c.name);
            let suffix = if db_path.exists() {
                count_docs(&db_path)
                    .map(|n| format!(", {n} docs"))
                    .unwrap_or_default()
            } else {
                " (not indexed)".to_string()
            };
            format!("{} ({}{})", c.name, c.path, suffix)
        })
        .collect();

    format!(
        "ir local search engine. Collections: {}. \
        Use `search` for hybrid BM25+vector retrieval, `get` or `multi_get` to retrieve \
        full document text by path, `status` for index health, \
        `update` to re-index after file changes.",
        cols.join("; ")
    )
}

// ── helpers ───────────────────────────────────────────────────────────────────

fn count_docs(db_path: &std::path::Path) -> Option<usize> {
    db::ensure_sqlite_vec();
    let conn = open_readonly(db_path).ok()?;
    conn.query_row(
        "SELECT COUNT(*) FROM documents WHERE active = 1",
        [],
        |row| row.get::<_, usize>(0),
    )
    .ok()
}

fn build_status() -> IrResult<StatusOutput> {
    let config = Config::load()?;
    let mut collections = Vec::new();
    for col in &config.collections {
        let db_path = collection_db_path(&col.name);
        let size_bytes = std::fs::metadata(&db_path).ok().map(|m| m.len());
        let indexed = size_bytes.is_some();
        let size_mb = size_bytes.unwrap_or(0) as f64 / 1_048_576.0;
        let doc_count = if indexed { count_docs(&db_path) } else { None };
        collections.push(CollectionStatus {
            name: col.name.clone(),
            path: col.path.clone(),
            indexed,
            size_mb,
            doc_count,
        });
    }
    Ok(StatusOutput {
        collections,
        daemon_running: crate::daemon::is_running(),
    })
}

fn run_update(collection: Option<&str>, force: bool) -> IrResult<Vec<UpdateResult>> {
    let config = Config::load()?;
    let cols: Vec<_> = match collection {
        Some(name) => {
            let c = config
                .get_collection(name)
                .ok_or_else(|| crate::error::Error::CollectionNotFound(name.to_string()))?;
            vec![c]
        }
        None => config.collections.iter().collect(),
    };

    let mut results = Vec::new();
    for col in cols {
        let db_path = collection_db_path(&col.name);
        let pp_aliases = col.preprocessor.as_deref().unwrap_or(&[]);
        let has_preprocessor = !config.resolve_preprocessor_commands(pp_aliases).is_empty();
        let db_conn = db::CollectionDb::open(&col.name, &db_path, has_preprocessor)?;
        let opts = index::UpdateOptions { force };
        let (added, updated, deactivated) = index::update(&db_conn, col, &opts, &config)?;
        results.push(UpdateResult {
            collection: col.name.clone(),
            added,
            updated,
            deactivated,
        });
    }
    Ok(results)
}

// ── helpers ───────────────────────────────────────────────────────────────────

fn open_readonly(path: &std::path::Path) -> std::result::Result<Connection, rusqlite::Error> {
    let conn = Connection::open_with_flags(path, OpenFlags::SQLITE_OPEN_READ_ONLY)?;
    let _ = conn.execute_batch("PRAGMA busy_timeout = 5000;");
    Ok(conn)
}

const SQL_EXACT: &str = "SELECT d.path, d.title, c.doc \
    FROM documents d JOIN content c ON d.hash = c.hash \
    WHERE d.path = ?1 AND d.active = 1 LIMIT 1";
const SQL_LIKE: &str = "SELECT d.path, d.title, c.doc \
    FROM documents d JOIN content c ON d.hash = c.hash \
    WHERE d.path LIKE ?1 AND d.active = 1 LIMIT 1";

fn fetch_document(path: &str, collection_filter: &[String]) -> IrResult<Option<DocContent>> {
    let config = Config::load()?;
    fetch_document_with_config(path, collection_filter, &config)
}

fn fetch_document_with_config(
    path: &str,
    collection_filter: &[String],
    config: &Config,
) -> IrResult<Option<DocContent>> {
    let cols: Vec<_> = if collection_filter.is_empty() {
        config.collections.iter().collect()
    } else {
        config.collections.iter().filter(|c| collection_filter.contains(&c.name)).collect()
    };

    db::ensure_sqlite_vec();

    for col in cols {
        let db_path = collection_db_path(&col.name);
        let conn = match open_readonly(&db_path) {
            Ok(c) => c,
            Err(rusqlite::Error::SqliteFailure(e, _))
                if e.code == rusqlite::ErrorCode::CannotOpen => continue,
            Err(e) => return Err(e.into()),
        };
        if let Some(doc) = lookup_in_conn(&conn, &col.name, path)? {
            return Ok(Some(doc));
        }
    }
    Ok(None)
}

/// Try exact, suffix, then substring path match. Stops at first hit.
fn lookup_in_conn(conn: &Connection, collection: &str, path: &str) -> IrResult<Option<DocContent>> {
    let suffix = format!("%/{path}");
    let substr = format!("%{path}%");
    let queries: &[(&str, &str)] = &[
        (SQL_EXACT, path),
        (SQL_LIKE, &suffix),
        (SQL_LIKE, &substr),
    ];
    for (sql, param) in queries {
        let row = conn.query_row(sql, rusqlite::params![param], |row| {
            Ok((
                row.get::<_, String>(0)?,
                row.get::<_, String>(1)?,
                row.get::<_, String>(2)?,
            ))
        });
        match row {
            Ok((doc_path, title, content)) => {
                return Ok(Some(DocContent {
                    collection: collection.to_string(),
                    path: doc_path,
                    title,
                    content,
                }));
            }
            Err(rusqlite::Error::QueryReturnedNoRows) => continue,
            Err(e) => return Err(e.into()),
        }
    }
    Ok(None)
}

// ── entry point ───────────────────────────────────────────────────────────────

pub async fn run(http: Option<u16>) -> IrResult<()> {
    match http {
        None => run_stdio().await,
        Some(port) => run_http(port).await,
    }
}

async fn run_stdio() -> IrResult<()> {
    let service = IrMcpServer::new()
        .serve(stdio())
        .await
        .map_err(|e| crate::error::Error::Other(e.to_string()))?;
    service
        .waiting()
        .await
        .map_err(|e| crate::error::Error::Other(e.to_string()))?;
    Ok(())
}

async fn run_http(port: u16) -> IrResult<()> {
    use rmcp::transport::streamable_http_server::{
        StreamableHttpServerConfig, StreamableHttpService,
        session::local::LocalSessionManager,
    };

    let service = StreamableHttpService::new(
        || Ok(IrMcpServer::new()),
        LocalSessionManager::default().into(),
        StreamableHttpServerConfig::default(),
    );

    let addr = format!("0.0.0.0:{port}");
    let listener = tokio::net::TcpListener::bind(&addr)
        .await
        .map_err(|e| crate::error::Error::Other(format!("bind {addr}: {e}")))?;
    eprintln!("ir MCP server listening on http://{addr}/mcp");

    let router = axum::Router::new().nest_service("/mcp", service);
    axum::serve(listener, router)
        .with_graceful_shutdown(async {
            tokio::signal::ctrl_c().await.ok();
        })
        .await
        .map_err(|e| crate::error::Error::Other(e.to_string()))
}
